/**
 * Generates seed/seed.sql with real bcrypt password hashes for the SIHADIR
 * schema (users / classes / class_members / sessions).
 *
 * IMPORTANT about face descriptors:
 *   The descriptors written here are PLACEHOLDERS (deterministic pseudo-random
 *   128-float vectors). Seed accounts exist immediately after a rebuild, but
 *   they will NOT match a real live face during check-in. For a real demo,
 *   re-register live on /register (recommended), or paste real captured
 *   descriptors into DESCRIPTORS below and re-run `npm run make-seed`.
 *
 * Usage: npx ts-node src/scripts/make-seed.ts
 */
import fs from "fs";
import path from "path";
import bcrypt from "bcryptjs";

const SEED_PASSWORD = "Passw0rd!";

interface SeedUser {
  name: string;
  email: string;
  role: "student" | "lecturer";
  student_id?: string;
  jurusan?: string;
  fakultas?: string;
}

// Domains here should match LECTURER_EMAIL_DOMAIN / STUDENT_EMAIL_DOMAIN.
const USERS: SeedUser[] = [
  { name: "Dr. Budi Santoso", email: "dosen@itb.ac.id", role: "lecturer" },
  { name: "Raqinnaja Axsali", email: "axsali@mahasiswa.itb.ac.id", role: "student", student_id: "18123054", jurusan: "Teknik Telekomunikasi", fakultas: "STEI" },
  { name: "Daffa Naufal", email: "daffa@mahasiswa.itb.ac.id", role: "student", student_id: "18123023", jurusan: "Teknik Telekomunikasi", fakultas: "STEI" },
  { name: "Ridho Radifa Al-Haq", email: "ridho@mahasiswa.itb.ac.id", role: "student", student_id: "18123010", jurusan: "Teknik Telekomunikasi", fakultas: "STEI" },
];

const DESCRIPTORS: Record<string, number[]> = {};

function placeholderDescriptor(seed: string): number[] {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const out: number[] = [];
  for (let i = 0; i < 128; i++) {
    h = (1103515245 * h + 12345) & 0x7fffffff;
    out.push(Number((((h % 1000) / 1000) * 0.4 - 0.2).toFixed(6)));
  }
  return out;
}

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  const lines: string[] = [];
  lines.push("-- AUTO-GENERATED by src/scripts/make-seed.ts. Do not edit by hand.");
  lines.push(`-- Default password for every account below: ${SEED_PASSWORD}`);
  lines.push("-- Descriptors are placeholders unless real ones were provided.");
  lines.push("");

  // Users (ids will be 1..N in insertion order on a fresh DB).
  for (const u of USERS) {
    const hash = await bcrypt.hash(SEED_PASSWORD, 10);
    const isStudent = u.role === "student";
    const desc = isStudent
      ? `CAST('${esc(JSON.stringify(DESCRIPTORS[u.student_id ?? u.email] ?? placeholderDescriptor(u.email)))}' AS JSON)`
      : "NULL";
    lines.push(
      `INSERT IGNORE INTO users (name, email, password_hash, role, student_id, jurusan, fakultas, face_descriptor, is_face_registered) VALUES (` +
        `'${esc(u.name)}', '${esc(u.email)}', '${hash}', '${u.role}', ` +
        `${u.student_id ? `'${esc(u.student_id)}'` : "NULL"}, ` +
        `${u.jurusan ? `'${esc(u.jurusan)}'` : "NULL"}, ` +
        `${u.fakultas ? `'${esc(u.fakultas)}'` : "NULL"}, ` +
        `${desc}, ${isStudent ? "TRUE" : "FALSE"});`
    );
  }

  lines.push("");
  lines.push("-- Demo class owned by the lecturer (id 1), join code DEMO01.");
  lines.push(
    "INSERT IGNORE INTO classes (id, name, mata_kuliah, kode_kelas, lecturer_id) VALUES " +
      "(1, 'Komputasi Awan 2026', 'ET3204', 'DEMO01', 1);"
  );
  lines.push("");
  lines.push("-- Enroll the 3 students (user ids 2,3,4) into the demo class.");
  lines.push(
    "INSERT IGNORE INTO class_members (class_id, student_id) VALUES (1, 2), (1, 3), (1, 4);"
  );
  lines.push("");
  lines.push("-- One active attendance session so check-in works right after seed.");
  lines.push(
    "INSERT IGNORE INTO sessions (id, class_id, name, is_active) VALUES (1, 1, 'Pertemuan 1 (Demo)', TRUE);"
  );
  lines.push("");

  const outPath = path.join(__dirname, "..", "..", "seed", "seed.sql");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
