/**
 * Generates seed/seed.sql with real bcrypt password hashes.
 *
 * IMPORTANT about face descriptors:
 *   The descriptors written here are PLACEHOLDERS (deterministic pseudo-random
 *   128-float vectors). They let the seed accounts exist immediately after a
 *   rebuild, but they will NOT match a real live face during check-in.
 *
 *   For a real demo you have two options:
 *     (a) Re-register live on /register (recommended — shows the enrollment
 *         flow), or
 *     (b) Paste real captured descriptors into the DESCRIPTORS map below and
 *         re-run `npm run make-seed`, then commit the regenerated seed.sql.
 *
 *   To capture a real descriptor: open the browser console on /register after
 *   the camera locks your face, and log the descriptor array.
 *
 * Usage: npx ts-node src/scripts/make-seed.ts
 */
import fs from "fs";
import path from "path";
import bcrypt from "bcryptjs";

// Default password for ALL seed accounts. Change before a real deployment.
const SEED_PASSWORD = "Passw0rd!";

interface SeedUser {
  id: string;
  name: string;
  email: string;
  role: "student" | "lecturer";
}

const USERS: SeedUser[] = [
  { id: "DOSEN001", name: "Dr. Budi Santoso", email: "dosen@kampus.ac.id", role: "lecturer" },
  { id: "10120001", name: "Anggota Satu", email: "anggota1@kampus.ac.id", role: "student" },
  { id: "10120002", name: "Anggota Dua", email: "anggota2@kampus.ac.id", role: "student" },
  { id: "10120003", name: "Anggota Tiga", email: "anggota3@kampus.ac.id", role: "student" },
];

// Optional: real captured descriptors keyed by user id. If absent, a
// deterministic placeholder is generated.
const DESCRIPTORS: Record<string, number[]> = {};

/** Deterministic pseudo-random descriptor so seed.sql is stable across runs. */
function placeholderDescriptor(seed: string): number[] {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const out: number[] = [];
  for (let i = 0; i < 128; i++) {
    h = (1103515245 * h + 12345) & 0x7fffffff;
    // face-api descriptors are roughly in [-0.2, 0.2].
    out.push(Number((((h % 1000) / 1000) * 0.4 - 0.2).toFixed(6)));
  }
  return out;
}

async function main() {
  const lines: string[] = [];
  lines.push("-- AUTO-GENERATED by src/scripts/make-seed.ts. Do not edit by hand.");
  lines.push(`-- Default password for every account below: ${SEED_PASSWORD}`);
  lines.push("-- Descriptors are placeholders unless real ones were provided.");
  lines.push("");

  for (const u of USERS) {
    const hash = await bcrypt.hash(SEED_PASSWORD, 10);
    const descriptor = DESCRIPTORS[u.id] ?? placeholderDescriptor(u.id);
    const descJson = JSON.stringify(descriptor).replace(/'/g, "''");
    lines.push(
      `INSERT IGNORE INTO students (id, name, email, password_hash, role, face_descriptor) VALUES (` +
        `'${u.id}', '${u.name}', '${u.email}', '${hash}', '${u.role}', ` +
        `CAST('${descJson}' AS JSON));`
    );
  }

  lines.push("");
  lines.push("-- A demo session that is open for the next 24h so check-in works right after seed.");
  lines.push(
    "INSERT IGNORE INTO class_sessions (id, course_name, lecturer_id, start_time, end_time, late_threshold_minutes, is_open) VALUES (" +
      "'demo-session-0001', 'Cloud Computing (Demo)', 'DOSEN001', " +
      "UTC_TIMESTAMP(), DATE_ADD(UTC_TIMESTAMP(), INTERVAL 24 HOUR), 15, 1);"
  );
  lines.push("");

  const outPath = path.join(__dirname, "..", "..", "seed", "seed.sql");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
